"South Indian":
  'Appetisers':
    - 'Soup'
    - 'Starter'
  'Main Course':
    - 'Tiffin'
    - 'Thali'
    - 'Curries'
  'Desserts':

"Andhra":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
    - 'Thali'
    - 'Curries'
  'Desserts':

"Bakery":
  'Snacks':
  'Cakes':
  'Beverages':

"Cafe":
  'Snacks':
  'Cakes':
  'Beverages':

"Chinese":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
    - 'Rice'
    - 'Noodles'
  'Desserts':

"Continental":
  'Appetisers':
    - 'Soups'
    - 'Starters'
    - 'Salads'
  'Main Course':
  'Desserts':

"Fast Food":
  'Snacks':
  'Meals':
  'Desserts':

"Hyderabadi":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
    - 'Biryanis'
  'Desserts':

"Mughlai":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
    - 'Biryanis'
  'Desserts':

"Pizza":
  'Pizzas':
  'Sides':

"Seafood":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
  'Desserts':

"Thai":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
  'Desserts':

"North Indian":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
    - 'Breads'
    - 'Curries'
    - 'Rice'
  'Desserts':

"Mexican":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
  'Desserts':

"Ice Cream":
  'Fruits':
  'Chocolate':
  'Nuts':

"Italian":
  'Appetisers':
    - 'Soups'
    - 'Starters'
  'Main Course':
    - 'Pastas'
    - 'Pizzas'
  'Desserts':
