development:
  adapter: mysql2
  encoding: utf8
  database: socialeater_development
  username: root
  host: 127.0.0.1
  port: 3306


production:
  adapter: mysql2
  encoding: utf8
  database: socialeater_production
  username: root
  password: ilikerandompasswords
  host: 127.0.0.1
  port: 3306
